steps:
  - name: ":rspec:"
    commands: 
      - bundle install
      - bundle exec rake db:drop
      - bundle exec rake db:create
      - RACK_ENV=test bundle exec rake db:migrate
      - bundle exec rspec
  
  - block: ":rocket: :rubygems: Publish :red_button:"
  
  - name: "Push :rubygems:"
      command: "./bin/deploy"
      branches: "main"