steps:
  - name: ":rspec:"
    commands: 
      - bundle install
      - bundle exec rake db:drop
      - bundle exec rake db:create
      - RACK_ENV=test bundle exec rake db:migrate
      - bundle exec rspec
    artifact_paths:
      - coverage/*
  
  - name: ":codeclimate: Report coverage"
    plugins:
      - jobready/codeclimate-test-reporter#v2.0:
          artifact: "coverage/.resultset.json"
          input_type: simplecov
          prefix: 'spec/'
  
  - block: ":rubygems: Publish :red_button:"
    branches: "main"
  
  - name: "Push :rubygems:"
    commands: "./bin/publish"
    branches: "main"