steps:
  - name: ":rspec:"
    commands: 
      - bundle install
      - dropdb ossorb-development --if-exists
      - dropdb ossorb-development --if-exists
      - createdb ossorb-development
      - cretedb ossorb-test
      - RACK_ENV=test bundle exec rake db:migrate
      - bundle exec rspec
    artifact_paths:
      - coverage/*
  
  - name: ":codeclimate:"
    plugins:
      - jobready/codeclimate-test-reporter#v2.0:
          artifact: "coverage/.resultset.json"
          input_type: simplecov
          prefix: '/var/lib/buildkite-agent/builds/enterprise-oss-bk-1/enterpriseoss/osso-rb/'
  
  - block: ":rubygems: Publish :red_button:"
    branches: "main"
  
  - name: "Push :rubygems:"
    commands: "./bin/publish"
    branches: "main"