development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: ossorb-development
  host: ''
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: ossorb-test
  host: ''
  port: 5432